In [2]:
import numpy as np

In [ ]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]])  # Corrected array formation
arr_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr_a[0]

array([1, 2, 3])

In [5]:
arr_a[1][1]

np.int64(5)

In [ ]:
arr_a[1, 1]

np.int64(5)

In [10]:
arr_a[:, 2]

array([3, 6])