In [ ]:
import numpy as np

In [2]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]])  # Corrected array formation
arr_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_a[0, 2] = 10
arr_a

array([[ 1,  2, 10],
       [ 4,  5,  6]])

In [4]:
arr_a[1] = 6
arr_a

array([[ 1,  2, 10],
       [ 6,  6,  6]])

In [5]:
arr_a[1] = [7, 8, 9]
arr_a

array([[ 1,  2, 10],
       [ 7,  8,  9]])

In [6]:
arr_a = 9
arr_a

9

In [7]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]])  # Corrected array formation
arr_a

array([[1, 2, 3],
       [4, 5, 6]])