In [2]:
import numpy as np

In [3]:
arr_b = np.array([[1, 2, 3], [4, 5, 6]])  # Corrected array formation
arr_b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr_a = np.array([7, 8, 9])  # Corrected array formation
arr_a

array([7, 8, 9])

In [6]:
arr_a + 2

array([ 9, 10, 11])

In [7]:
arr_b * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [11]:
list_a = [1, 2, 3]
list_a + [2]

[1, 2, 3, 2]

In [12]:
arr_a + arr_b[0]

array([ 8, 10, 12])

In [13]:
arr_a + arr_b

array([[ 8, 10, 12],
       [11, 13, 15]])