In [1]:
import numpy as np

In [2]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]])  # Corrected array formation
arr_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]], dtype="float32")  # Corrected array formation
arr_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [ ]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float16)
arr_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [ ]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.complex64)
arr_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [ ]:
arr_a = np.array([[1, 2, 0], [0, 5, 6]], dtype=np.bool)
arr_a

array([[ True,  True, False],
       [False,  True,  True]])

In [9]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.str_)
arr_a

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')