In [1]:
import numpy as np

In [3]:
arr_a = np.array([1, 2, 3])
arr_a

array([1, 2, 3])

In [ ]:
arr_b = np.array([[1], [2]])
arr_b

array([[1],
       [2]])

In [ ]:
matrix_c = np.array([[1, 2, 3], [4, 5, 6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

  ## Broadcasting

In [8]:
np.add(arr_a, matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

https://numpy.org/doc/stable/reference/ufuncs.html

## Universal Functions