In [1]:
import numpy as np

In [3]:
arr_a = np.array([1, 2, 3])
arr_a

array([1, 2, 3])

In [ ]:
arr_b = np.array([[1], [2]])
arr_b

array([[1],
       [2]])

In [ ]:
matrix_c = np.array([[1, 2, 3], [4, 5, 6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

  ## Broadcasting

In [8]:
np.add(arr_a, matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

## Universal Functions

https://numpy.org/doc/stable/reference/ufuncs.html

## Type Casting

In [9]:
np.add(arr_a, matrix_c, dtype=np.float64)

array([[2., 4., 6.],
       [5., 7., 9.]])

In [11]:
np.add(arr_a, matrix_c, dtype=np.int64)

array([[2, 4, 6],
       [5, 7, 9]])

## Running over axis

In [12]:
np.mean(matrix_c, axis=0)  # Column-wise mean , axis=0 : down the rows

array([2.5, 3.5, 4.5])

In [13]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.mean(matrix_c, axis=1)  # Row-wise mean , axis=1 : across the columns

array([2., 5.])